@props([
    'facultyLabel' => 'Course Faculty / Tutor',
    'hodLabel' => 'Head of Department',
    'principalLabel' => 'Principal',
    'showPrincipal' => true,
    'customSignatures' => []
])

<div class="mt-12 pt-6 border-t border-slate-300 break-inside-avoid">
    <div class="grid {{ $showPrincipal ? 'grid-cols-3' : 'grid-cols-2' }} gap-8 text-center text-xs text-slate-800">
        @if(!empty($customSignatures))
            @foreach($customSignatures as $sig)
                <div class="space-y-12">
                    <div class="h-10"></div>
                    <div class="border-t border-slate-400 pt-1.5 font-semibold">
                        {{ $sig }}
                    </div>
                </div>
            @endforeach
        @else
            <div class="space-y-12">
                <div class="h-10"></div>
                <div class="border-t border-slate-400 pt-1.5 font-semibold">
                    {{ $facultyLabel }}
                </div>
            </div>
            <div class="space-y-12">
                <div class="h-10"></div>
                <div class="border-t border-slate-400 pt-1.5 font-semibold">
                    {{ $hodLabel }}
                </div>
            </div>
            @if($showPrincipal)
                <div class="space-y-12">
                    <div class="h-10"></div>
                    <div class="border-t border-slate-400 pt-1.5 font-semibold">
                        {{ $principalLabel }}
                    </div>
                </div>
            @endif
        @endif
    </div>
    <div class="mt-6 text-center text-[10px] text-slate-400 font-mono">
        Official Document Generated by CampusLynk Academic Platform · Verified for Institutional Records
    </div>
</div>
